- alias: Turn off all lights at night
  trigger:
    platform: time
    at: '23:30:00'
  action:
    - service: light.turn_off
      entity_id: group.all_lights
    - service: notify.pushbullet
      data:
        message: "All lights turned off"

- alias: Turn off all lights in the morning
  trigger:
    platform: time
    at: '08:30:00'
  action:
    - service: light.turn_off
      entity_id: group.all_lights
    - service: notify.pushbullet
      data:
        message: "All lights turned off"   

- alias: Turn lights on at sunset
  trigger:
    platform: sun
    event: sunset
  action:
    - service: light.turn_on
      entity_id: group.all_lights
    - service: notify.pushbullet
      data:
        message: "All lights turned on"

- alias: Update notifications
  trigger:
    platform: state
    entity_id: updater.updater
  action:
    - service: notify.pushbullet
      data: 
        title: 'New Home Assistant Release'
        message: "Home Assistant  {{ states.updater.updater.state }}  is now available."
