- alias: Jubilee Line Delayed
  trigger:
    platform: state
    entity_id: sensor.jubilee_line_delayed
    to: 'true'
  condition:
    - condition: time
      after: '05:00:00'
      before: '22:00:00'
  action:
    - service: notify.pushbullet
      data:
        title: "Jubilee Line Update"
        message: "{{ states.sensor.jubilee.state }}"

- alias: Metropolitan Line Delayed
  trigger:
    platform: state
    entity_id: sensor.met_line_delayed
    to: 'true'
  condition:
    - condition: time
      after: '05:00:00'
      before: '22:00:00'
  action:
    - service: notify.pushbullet
      data:
        title: "Metropolitan Line Update"
        message: "{{ states.sensor.metropolitan.state }}"

- alias: Start webcam recording when Adam is not home
  trigger:
    platform: state
    entity_id: group.adams_devices
    to: 'not_home'
  condition:
    - condition: state
      entity_id: input_boolean.working_from_home
      state: 'off'
  action:
    - service: switch.turn_on
      entity_id: switch.office_camera_switch 
    - service: notify.pushbullet
      data:
        message: "Office camera started recording"

- alias: Stop webcam recording when Adam gets home
  trigger:
    platform: state
    entity_id: group.adams_devices 
    to: 'home'
  condition:
    - condition: state
      entity_id: input_boolean.working_from_home
      state: 'off'
  action:
    - service: switch.turn_off
      entity_id: switch.office_camera_switch 
    - service: notify.pushbullet
      data:
        message: "Office camera stopped recording"

- alias: Turn off all lights at night
  trigger:
    platform: time
    at: '23:30:00'
  action:
    - service: light.turn_off
      entity_id: group.all_lights
    - service: notify.pushbullet
      data:
        message: "All lights turned off"

- alias: Turn off all lights in the morning
  trigger:
    platform: time
    at: '08:30:00'
  action:
    - service: light.turn_off
      entity_id: group.all_lights
    - service: notify.pushbullet
      data:
        message: "All lights turned off"   

- alias: Turn off all lights if no one is home
  trigger:
    - platform: state
      entity_id: group.family
      to: 'not_home'
  condition:  
    - condition: state
      entity_id: group.all_lights
      state: 'on'
  action:
    - service: light.turn_off
      entity_id: group.all_lights
    - service: notify.pushbullet
      data:
        message: "Turned all lights off as no one is home"

- alias: Turn office lights on at sunset if Adam is home
  trigger:
    - platform: sun
      event: sunset
      offset: "-00:15:00"
    - platform: state
      entity_id: group.adams_devices
      to: 'home'
  condition:  
    condition: and
    conditions:
      - condition: sun
        after: sunset
        after_offset: "-00:15:00"
      - condition: state
        entity_id: group.adams_devices
        state: 'home'
  action:
    - service: light.turn_on
      entity_id: group.office_lights
    - service: notify.pushbullet
      data:
        message: "Office lights turned on"

- alias: Turn living room lights on at sunset if anyone is home
  trigger:
    - platform: sun
      event: sunset
      offset: "-00:15:00"
    - platform: state
      entity_id: group.family
      to: 'home'
  condition:  
    condition: and
    conditions:
      - condition: sun
        after: sunset
        after_offset: "-00:15:00"
      - condition: state
        entity_id: group.family
        state: 'home'
  action:
    - service: light.turn_on
      entity_id: group.living_room_lights
    - service: notify.pushbullet
      data:
        message: "Living room lights turned on"

- alias: Update notifications
  trigger:
    platform: state
    entity_id: updater.updater
  action:
    - service: notify.pushbullet
      data: 
        title: 'New Home Assistant Release'
        message: "Home Assistant  {{ states.updater.updater.state }}  is now available."
