homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude 
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0
  # metric for Metric, imperial for Imperial
  #unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/London

  customize: !include customise.yaml

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:
  themes: !include themes.yaml

# Enables configuration UI
config:

http:
  # Uncomment this to add a password (recommended!)
  api_password: !secret http_password

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Text to speech
tts:
  platform: google

recorder:
  purge_interval: 2
  purge_keep_days: 5

logger:
  default: warning
  logs:
    requests.packages.urllib3.connectionpool: critical
    requests.packages.urllib3.response: critical

google:
  client_id: !secret google_client_id 
  client_secret: !secret google_client_secret 

ios:

cloud:

light:
  - platform: hue
    host: 192.168.0.12

automation: !include automations.yaml
camera: !include cameras.yaml
device_tracker: !include device_tracker.yaml
group: !include groups.yaml
input_boolean: !include input_booleans.yaml
input_number: !include input_numbers.yaml
media_player: !include media_players.yaml
notify: !include notifiers.yaml
sensor: !include sensors.yaml
shell_command: !include shell_command.yaml
switch: !include switches.yaml        
weblink: !include weblink.yaml        
zone: !include zones.yaml
