- platform: nmap_tracker
  hosts: 192.168.0.1/48
  home_interval: 10
  track_new_devices: true
  consider_home: 180
  scan_options: " -PS135,445 -F --host-timeout 5s"
  exclude:
    - 192.168.0.12 # Hue Bridge
    - 192.168.0.15 # Chromecast
    - 192.168.0.16 # TiVo Box
    - 192.168.0.23 # TV
