- platform: nmap_tracker
  hosts: 192.168.0.1-255
  home_interval: 350
  scan_options: " -PS135,445 -F --host-timeout 5s"
  interval_seconds: 1800
  exclude:
    - 192.168.0.12 # Hue Bridge
    - 192.168.0.15 # Chromecast
    - 192.168.0.16 # TiVo Box
    - 192.168.0.23 # TV

- platform: bluetooth_tracker
  track_new_devices: true