- platform: bitcoin
  display_options:
    - exchangerate
    - trade_volume_btc
    - difficulty
    - hash_rate

- platform: command_line
  name: log_db_file_size
  command: "du -m /home/homeassistant/.homeassistant/home-assistant_v2.db | cut -f1"
  unit_of_measurement: 'MB'
  value_template: '{{ value | int - 1 }}'

- platform: google_travel_time
  api_key: !secret google_api_key 
  name: Time to Work
  origin: zone.home
  destination: zone.work
  options:
    mode: transit

- platform: google_travel_time
  api_key: !secret google_api_key 
  name: Time to Hockey Training
  origin: zone.home
  destination: zone.hockey
  options:
    mode: transit         

- platform: london_underground
  line:
    - Bakerloo
    - Central
    - Circle
    - District
    - DLR
    - Hammersmith & City
    - Jubilee
    - London Overground
    - Metropolitan
    - Northern
    - Piccadilly
    - TfL Rail
    - Victoria
    - Waterloo & City

- platform: pi_hole      
  host: localhost:9000

- platform: steam_online
  api_key: !secret steam_api_key
  accounts:
    - !secret steam_uid

- platform: systemmonitor
  resources:
    - type: processor_use
    - type: disk_use_percent
      arg: /home
    - type: memory_free
    - type: since_last_boot

- platform: time_date
  display_options:
    - 'time'
    - 'date'      

# - platform: uber
#   server_token: !secret uber_server_token      

- platform: wunderground
  api_key: !secret wu_api_key
  monitored_conditions:
    - alerts
    - feelslike_c
    - precip_today_string
    - temp_c
    - temp_high_1d_c
    - temp_low_1d_c
    - wind_string

# Templates

- platform: template
  sensors:
    # devices
    adams_laptop:
      value_template: '{% if is_state("device_tracker.adams_laptop", "home") %}Online{% else %}Offline{% endif %}'
      friendly_name: 'Adams Laptop'
      icon_template: mdi:laptop-windows

    adams_pc:
      value_template: '{% if is_state("device_tracker.adams_pc", "home") %}Online{% else %}Offline{% endif %}'
      friendly_name: 'Adams PC'
      icon_template: mdi:windows

    kitchen_home_mini:
      value_template: '{% if is_state("device_tracker.kitchen_home_mini", "home") %}Online{% else %}Offline{% endif %}'
      friendly_name: 'Kitchen Home Mini'
      icon_template: mdi:google

    living_room_home:
      value_template: '{% if is_state("device_tracker.living_room_home", "home") %}Online{% else %}Offline{% endif %}'
      friendly_name: 'Living Room Home'
      icon_template: mdi:google

    office_home_mini:
      value_template: '{% if is_state("device_tracker.office_home_mini", "home") %}Online{% else %}Offline{% endif %}'
      friendly_name: 'Office Home Mini'
      icon_template: mdi:google

    printer:
      value_template: '{% if is_state("device_tracker.printer", "home") %}On{% else %}Off{% endif %}'
      friendly_name: 'Printer'

    router:
      value_template: '{% if is_state("device_tracker.router", "home") %}Online{% else %}Offline{% endif %}'
      friendly_name: 'Router'    

    steam_link:
      value_template: '{% if is_state("device_tracker.steam_link", "home") %}Online{% else %}Offline{% endif %}'
      friendly_name: 'Steam Link'
      icon_template: mdi:steam

    # calendars
    adams_calendar:
      value_template: >
        {{ strptime(states.calendar.adamshort1994gmailcom.attributes.start_time, "%Y-%m-%d %H:%M:%S").strftime("%d %B, %H:%M") }}:
        {{ states.calendar.adamshort1994gmailcom.attributes.message }}
      friendly_name: Adam
      unit_of_measurement: ''
      icon_template: mdi:calendar

    catherines_calendar:
      value_template: >
        {{ strptime(states.calendar.cathybrooks94gmailcom.attributes.start_time, "%Y-%m-%d %H:%M:%S").strftime("%d %B, %H:%M") }}:
        {{ states.calendar.cathybrooks94gmailcom.attributes.message }}
      friendly_name: Catherine
      unit_of_measurement: ''
      icon_template: mdi:calendar

    f1_calendar:
      value_template: >
        {{ strptime(states.calendar.formula_one_calendar_by_f1_fanatic.attributes.start_time, "%Y-%m-%d %H:%M:%S").strftime("%d %B, %H:%M") }}:
        {{ states.calendar.formula_one_calendar_by_f1_fanatic.attributes.message }}
      friendly_name: F1 Events
      unit_of_measurement: ''
      icon_template: mdi:car-sports

    liverpool_calendar:
      value_template: >
        {{ strptime(states.calendar.liverpool_fc_calendar__fixtures__results.attributes.start_time, "%Y-%m-%d %H:%M:%S").strftime("%d %B, %H:%M") }}:
        {{ states.calendar.liverpool_fc_calendar__fixtures__results.attributes.message }}
      friendly_name: Liverpool Fixtures
      unit_of_measurement: ''
      icon_template: mdi:soccer

    hockey_calendar:
      value_template: >
        {{ strptime(states.calendar.hhc_mens_2s_.attributes.start_time, "%Y-%m-%d %H:%M:%S").strftime("%d %B, %H:%M") }}:
        {{ states.calendar.hhc_mens_2s_.attributes.message }}
      friendly_name: Hockey
      unit_of_measurement: ''
      icon_template: mdi:soccer

    # sensors/other
    date:
      value_template: '{{ as_timestamp(sensor.date) | timestamp_custom("%A %d %b %Y") }}'
      friendly_name: 'Date'

    jubilee_line_delayed:
      entity_id: sensor.jubilee
      value_template: '{% if states("sensor.jubilee") != "Good Service" %}true{% else %}false{% endif %}'

    met_line_delayed:
      entity_id: sensor.metropolitan
      value_template: '{% if states("sensor.metropolitan") != "Good Service" %}true{% else %}false{% endif %}'

    steam_game:
      value_template: '{{ states.sensor.steam_76561198043609312.attributes.Game }}'
      friendly_name: 'Currently Playing'
      icon_template: mdi:google-controller

    sunrise:
      value_template: '{{ as_timestamp(states.sun.sun.attributes.next_rising) | timestamp_custom("%-H:%M") }}'
      friendly_name: 'Sunrise'
      icon_template: mdi:weather-sunset-up

    sunset:
      value_template: '{{ as_timestamp(states.sun.sun.attributes.next_setting) | timestamp_custom("%-H:%M") }}'
      friendly_name: 'Sunset'
      icon_template: mdi:weather-sunset-down