- platform: bitcoin
  display_options:
    - exchangerate
    - trade_volume_btc
    - difficulty
    - hash_rate

- platform: google_travel_time
  api_key: !secret google_api_key 
  name: Time to Work
  origin: zone.home
  destination: zone.work
  options:
    mode: transit

- platform: london_underground
  line:
    - Bakerloo
    - Central
    - Circle
    - District
    - DLR
    - Hammersmith & City
    - Jubilee
    - London Overground
    - Metropolitan
    - Northern
    - Piccadilly
    - TfL Rail
    - Victoria
    - Waterloo & City

- platform: pi_hole      

- platform: speedtest
  minute: 30
  hour:
    - 0
    - 6
    - 12
    - 18
  monitored_conditions:
    - ping
    - download
    - upload

- platform: systemmonitor
  resources:
    - type: processor_use
    - type: disk_use_percent
      arg: /home
    - type: memory_free
    - type: since_last_boot

- platform: time_date
  display_options:
    - 'time'
    - 'date'      

- platform: uber
  server_token: !secret uber_server_token      

- platform: yr
  monitored_conditions:
    - temperature
    - symbol
    - windSpeed
    - humidity
    - cloudiness      

# Templates

- platform: template
  sensors:
    adams_pc:
      value_template: '{% if is_state("device_tracker.ac9e17844eab", "home") %}online{% else %}offline{% endif %}'
      friendly_name: 'Adams PC'
      icon_template: mdi:windows
    adams_laptop:
      value_template: '{% if is_state("device_tracker.485ab67eab29", "home") %}online{% else %}offline{% endif %}'
      friendly_name: 'Adams Laptop'
      icon_template: mdi:laptop-windows
    router:
      value_template: '{% if is_state("device_tracker.400d1034ff40", "home") %}online{% else %}offline{% endif %}'
      friendly_name: 'Router'    
    steam_link:
      value_template: '{% if is_state("device_tracker.e0319e22699e", "home") %}online{% else %}offline{% endif %}'
      friendly_name: 'Steam Link'
      icon_template: mdi:steam
