- platform: bitcoin
  display_options:
    - exchangerate
    - trade_volume_btc
    - difficulty
    - hash_rate

- platform: london_underground
  line:
    - Bakerloo
    - Central
    - Circle
    - District
    - DLR
    - Hammersmith & City
    - Jubilee
    - London Overground
    - Metropolitan
    - Northern
    - Piccadilly
    - TfL Rail
    - Victoria
    - Waterloo & City

- platform: systemmonitor
  resources:
    - type: processor_use
    - type: disk_use_percent
      arg: /home
    - type: memory_free
    - type: since_last_boot

- platform: uber
  server_token: !secret uber_server_token 

- platform: time_date
  display_options:
    - 'time'
    - 'date'

- platform: pi_hole

- platform: snmp
  name: snmp_wan_in
  host: 192.168.0.1
  baseoid: 1.3.6.1.2.1.2.2.1.10.2

- platform: snmp
  name: snmp_wan_out
  host: 192.168.0.1
  baseoid: 1.3.6.1.2.1.2.2.1.16.2

# Templates

- platform: template
  sensors:
    adams_pc:
      value_template: '{% if is_state("device_tracker.ac9e17844eab", "home") %}online{% else %}offline{% endif %}'
      friendly_name: 'Adams PC'
      icon_template: mdi:windows

# https://community.home-assistant.io/t/snmp-bandwidth-monitor/7122       

- platform: template
  sensors:
    internet_speed_in:
      friendly_name: 'Internet Speed'
      value_template: '{{ ((states.input_slider.internet_traffic_delta_in.state | float ) / 1000000 ) | round(2) }}'
      unit_of_measurement: 'Mbps'

- platform: template
  sensors:
    internet_speed_out:
      friendly_name: 'Internet Speed'
      value_template: '{{ ((states.input_slider.internet_traffic_delta_out.state | float ) / 1000000 ) | round(2) }}'
      unit_of_measurement: 'Mbps'

- platform: statistics
  name: 'WAN Traffic IN'
  entity_id: sensor.internet_speed_in

- platform: statistics
  name: 'WAN Traffic OUT'
  entity_id: sensor.internet_speed_out
