- platform: bitcoin
  display_options:
    - exchangerate
    - trade_volume_btc
    - difficulty
    - hash_rate

- platform: command_line
  name: log_db_file_size
  command: "du -m /home/homeassistant/.homeassistant/home-assistant_v2.db | cut -f1"
  unit_of_measurement: 'MB'
  value_template: '{{ value | int - 1 }}'

- platform: google_travel_time
  api_key: !secret google_api_key 
  name: Time to Work
  origin: zone.home
  destination: zone.work
  options:
    mode: transit

- platform: google_travel_time
  api_key: !secret google_api_key 
  name: Time to Hockey Training
  origin: zone.home
  destination: zone.hockey
  options:
    mode: transit         

- platform: london_underground
  line:
    - Bakerloo
    - Central
    - Circle
    - District
    - DLR
    - Hammersmith & City
    - Jubilee
    - London Overground
    - Metropolitan
    - Northern
    - Piccadilly
    - TfL Rail
    - Victoria
    - Waterloo & City

- platform: pi_hole      
  host: localhost:9000

- platform: snmp
  host: 192.168.0.14
  name: pc_up_time
  baseoid: 1.3.6.1.4.1.311.1.1.3.1.1.33.14

- platform: systemmonitor
  resources:
    - type: processor_use
    - type: disk_use_percent
      arg: /home
    - type: memory_free
    - type: since_last_boot

- platform: time_date
  display_options:
    - 'time'
    - 'date'      

- platform: uber
  server_token: !secret uber_server_token      

- platform: yr
  monitored_conditions:
    - temperature
    - symbol
    - windSpeed
    - humidity
    - cloudiness      

# Templates

- platform: template
  sensors:
    adams_laptop:
      value_template: '{% if is_state("device_tracker.adams_laptop", "home") %}online{% else %}offline{% endif %}'
      friendly_name: 'Adams Laptop'
      icon_template: mdi:laptop-windows
    adams_pc:
      value_template: '{% if is_state("device_tracker.adams_pc", "home") %}online{% else %}offline{% endif %}'
      friendly_name: 'Adams PC'
      icon_template: mdi:windows
    google_home:
      value_template: '{% if is_state("device_tracker.google_home", "home") %}online{% else %}offline{% endif %}'
      friendly_name: 'Google Home'
      icon_template: mdi:google
    router:
      value_template: '{% if is_state("device_tracker.router", "home") %}online{% else %}offline{% endif %}'
      friendly_name: 'Router'    
    steam_link:
      value_template: '{% if is_state("device_tracker.steam_link", "home") %}online{% else %}offline{% endif %}'
      friendly_name: 'Steam Link'
      icon_template: mdi:steam

    adams_calendar:
      value_template: >
        {{ strptime(states.calendar.adamshort1994gmailcom.attributes.start_time, "%Y-%m-%d %H:%M:%S").strftime("%d %B, %H:%M") }}:
        {{ states.calendar.adamshort1994gmailcom.attributes.message }}
      friendly_name: Adam's Next Event
      unit_of_measurement: ''
      icon_template: mdi:calendar

    catherines_calendar:
      value_template: >
        {{ strptime(states.calendar.cathybrooks94gmailcom.attributes.start_time, "%Y-%m-%d %H:%M:%S").strftime("%d %B, %H:%M") }}:
        {{ states.calendar.cathybrooks94gmailcom.attributes.message }}
      friendly_name: Catherine's Next Event
      unit_of_measurement: ''
      icon_template: mdi:calendar
