- platform: wake_on_lan
  mac_address: !secret pc_mac_address 
  name: "Wake Adam's PC"
  host: 192.168.0.14

- platform: command_line
  switches:
    office_camera_switch:
      command_on: "python3 /home/homeassistant/.homeassistant/camera_recording.py 1 true"
      command_off: "python3 /home/homeassistant/.homeassistant/camera_recording.py 1 false"
      friendly_name: Office Camera Recording
